CREATE DATABASE Tela_Cadastro2
GO
USE Tela_Cadastro2
GO
CREATE TABLE EMPRESA(
ID_EMPRESA INT PRIMARY KEY IDENTITY NOT NULL,
Nome_Empresa VARCHAR(150) NOT NULL
)

CREATE TABLE UF(
ID_UF INT PRIMARY KEY IDENTITY NOT NULL,
Sigla CHAR(2) 
)

CREATE TABLE CARGO(
ID_CARGO INT PRIMARY KEY IDENTITY NOT NULL,
ID_EMPRESA INT NOT NULL, 
FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
Nome_cargo VARCHAR(150) NOT NULL
)

CREATE TABLE CIDADE(
ID_CIDADE INT PRIMARY KEY IDENTITY NOT NULL,
ID_UF INT NOT NULL,
FOREIGN KEY (ID_UF) REFERENCES UF (ID_UF),
Nome_Cidade VARCHAR(150) NOT NULL
)

CREATE TABLE COLABORADOR(
ID_COLABORADOR INT PRIMARY KEY IDENTITY NOT NULL,
ID_CARGO INT NOT NULL,
FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID_CARGO),
ID_CIDADE INT NOT NULL,
FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE),
ID_Empresa int not NULL,
FOREIGN KEY (ID_Empresa) REFERENCES Empresa (ID_Empresa),
Nome_colaborador VARCHAR(200),
Email VARCHAR(100)
)

CREATE TABLE CONTATO(
ID_CONTATO INT PRIMARY KEY IDENTITY NOT NULL,
ID_COLABORADOR INT NOT NULL,
FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR (ID_COLABORADOR),
DDD TINYINT NOT NULL,
Numero_Colaborador BIGINT NOT NULL,
Whatsapp BIT NOT NULL
)

INSERT INTO EMPRESA (Nome_Empresa) VALUES 
('SMN INGÁ'),
('SMN JOÃO PESSOA'),
('SMN FRANCA'),
('SMN PASSOS');


INSERT INTO CARGO (ID_EMPRESA, Nome_cargo) VALUES 
(1, 'Analista de Negócio'),
(1, 'Desenvolvedor'),
(2, 'Analista de Negócio'),
(2, 'Desenvolvedor'),
(3, 'Analista de Negócio'),
(3, 'Desenvolvedor'),
(4, 'Analista de Negócio'),
(4, 'Desenvolvedor');

INSERT INTO UF (Sigla) VALUES 
('PB'),
('SP'),
('RJ'),
('SC');

INSERT INTO CIDADE (ID_UF, Nome_Cidade) VALUES 
(1, 'INGÁ'),
(3, 'RIO DE JANEIRO'),
(1, 'JOÃO PESSOA'),
(2, 'FRANCA'),
(4, 'CHAPECÓ');

GO
ALTER PROC Inserir_Dados (@IdCargo INT, @IdCidade INT, @NomeColaborador VARCHAR(150), @EmailColaborador VARCHAR(100),
@IdColaborador INT, @DDDColaborador TINYINT, @NumeroColaborador BIGINT, @Whatasapp BIT)
AS
BEGIN

	INSERT INTO COLABORADOR (ID_CARGO, ID_CIDADE, Nome_colaborador, Email) VALUES (@IdCargo, @IdCidade, @NomeColaborador, @EmailColaborador)

	DECLARE @UltimoIdColaborador INT
	SELECT TOP 1 @UltimoIdColaborador = ID_COLABORADOR FROM COLABORADOR

	INSERT INTO CONTATO (ID_COLABORADOR, DDD, Numero_Colaborador, Whatsapp) VALUES (@IdColaborador, @DDDColaborador, @NumeroColaborador, @Whatasapp)
END
GO

EXEC Inserir_Dados 
@IdCargo
@IdCidade
@NomeColaborador 
@EmailColaborador 
@IdColaborador 
@DDDColaborador 
@NumeroColaborador 
@Whatasapp
GO

CREATE PROCEDURE Deletar_Dados (
@IDColaborador INT)
AS
BEGIN
  DELETE SELECT Nome_Empresa, Sigla, Nome_colaborador, Email, ID_CONTATO, DDD, Numero_Colaborador, Whatsapp
  FROM EMPRESA, UF, CARGO, CIDADE, COLABORADOR, CONTATO
  WHERE ID_COLABORADOR = @IDColaborador
END


CREATE TRIGGER Inserindo_Dados
ON 
INSTEAD OF 
AS
INSERT INTO 