ALTER PROC [dbo].[SP_UPATUALIZARDADOS](
	@ID_CALOBORADOR INT,
	@ID_EMPRESA INT = NULL,
	@CONTATO INT,
	@NOME_COLABORADOR VARCHAR (200) = NULL,
	@EMAIL_COLABORADOR VARCHAR (100) = NULL,
	@DDD TINYINT = NULL,
	@NUMERO BIGINT = NULL,
	@WHATSAPP BIT = NULL, 
	@CARGO INT = NULL, 
	@CIDADE INT = NULL 
	)
	
		AS

		/*
		Documentação
		Arquivo FONTE.....: ATIVIDADE.SQL
		Objetivo..........: ATUALIZAR DADOS DA TABELA COLABORADOR
		Autor........: SMN - LUCAS MELO
		Data.........: 11/11/23
		EX..............:EXEC [dbo].[SP_UPATUALIZARDADOS] 
		*/ 

		BEGIN 

		UPDATE COLABORADOR SET 
			ID_Empresa = COALESCE(@ID_EMPRESA, ID_Empresa),
			Nome_colaborador = COALESCE (@NOME_COLABORADOR, Nome_colaborador),
			Email = COALESCE ( @EMAIL_COLABORADOR, email ),
			ID_CARGO = COALESCE ( @CARGO, ID_CARGO),
			ID_CIDADE = COALESCE ( @CIDADE, ID_CIDADE)
			WHERE ID_COLABORADOR = @ID_CALOBORADOR

			UPDATE CONTATO SET
			DDD = COALESCE ( @DDD, DDD),
			Numero_Colaborador = COALESCE ( @NUMERO, Numero_colaborador),
			Whatsapp = COALESCE (@WHATSAPP, Whatsapp )
			WHERE ID_CONTATO = @CONTATO
		END

	GO